"""Guard the notebooks against the two ways they silently rot.

The notebooks are generated by ``scripts/build_notebook.py`` but committed *executed*, with their
outputs embedded, because a notebook without its figures renders as a blank page on GitHub. That
split is a footgun in both directions:

1. **Drift.** Someone edits a notebook in Jupyter, commits it, and the next ``make notebook``
   silently reverts the edit -- the builder, not the notebook, is the source of truth.
2. **Stripping.** Someone runs ``make notebook`` without ``make notebook-run`` and commits the
   result. The diff looks like a 900-line deletion, the notebooks still "work", and every figure
   in the rendered documentation disappears.

Both happened during v0.4 development. These tests are cheap -- they parse JSON and never launch a
kernel -- so they run on every commit and cost nothing.
"""

from __future__ import annotations

import importlib.util
import json
import sys
from pathlib import Path
from typing import Any

import pytest

REPO_ROOT = Path(__file__).resolve().parents[1]
NOTEBOOKS = REPO_ROOT / "notebooks"
BUILDER = REPO_ROOT / "scripts" / "build_notebook.py"


def _load_builder() -> Any:
    """Import ``scripts/build_notebook.py`` without making ``scripts/`` an importable package."""
    spec = importlib.util.spec_from_file_location("_astracell_build_notebook", BUILDER)
    assert spec is not None and spec.loader is not None
    module = importlib.util.module_from_spec(spec)
    sys.modules[spec.name] = module
    spec.loader.exec_module(module)
    return module


def _read(path: Path) -> dict[str, Any]:
    notebook: dict[str, Any] = json.loads(path.read_text(encoding="utf-8"))
    return notebook


def _code_cells(notebook: dict[str, Any]) -> list[dict[str, Any]]:
    return [cell for cell in notebook["cells"] if cell["cell_type"] == "code"]


_BUILDER = _load_builder()

# (filename stem, the builder's cell list) -- the mapping the builder's ``main()`` writes.
NOTEBOOK_CELLS: list[tuple[str, list[dict[str, Any]]]] = [
    ("01_identifiability_study", _BUILDER.CELLS_01),
    ("02_calibrated_abstention", _BUILDER.CELLS_02),
    ("03_external_plant_gate", _BUILDER.CELLS_03),
    ("04_external_positive_control", _BUILDER.CELLS_04),
]
NOTEBOOK_NAMES = [name for name, _ in NOTEBOOK_CELLS]


@pytest.mark.parametrize(("name", "cells"), NOTEBOOK_CELLS, ids=NOTEBOOK_NAMES)
def test_the_committed_notebook_matches_its_generator(name: str, cells: list[dict]) -> None:
    """The builder is the source of truth; a hand-edit in Jupyter would be silently reverted."""
    on_disk = _read(NOTEBOOKS / f"{name}.ipynb")["cells"]

    assert len(on_disk) == len(cells), (
        f"{name}: {len(on_disk)} cells on disk, {len(cells)} in the builder. "
        "Run `make notebook && make notebook-run`."
    )
    for index, (disk_cell, built_cell) in enumerate(zip(on_disk, cells, strict=True)):
        assert disk_cell["cell_type"] == built_cell["cell_type"], f"{name}: cell {index} type"
        assert "".join(disk_cell["source"]) == "".join(built_cell["source"]), (
            f"{name}: cell {index} source differs from scripts/build_notebook.py. "
            "Edit the builder, not the notebook."
        )


@pytest.mark.parametrize("name", NOTEBOOK_NAMES)
def test_the_committed_notebook_kept_its_outputs(name: str) -> None:
    """`make notebook` strips outputs. Committing that result blanks the rendered docs."""
    code = _code_cells(_read(NOTEBOOKS / f"{name}.ipynb"))

    # Not every code cell emits something -- a pure-import cell legitimately produces nothing --
    # so the invariant is that the notebook as a whole was executed, not that each cell spoke.
    executed = [cell for cell in code if cell.get("outputs")]
    assert executed, (
        f"{name}: every code cell is stripped, so this notebook was committed straight from "
        "`make notebook`. Run `make notebook-run` to restore its outputs before committing."
    )


@pytest.mark.parametrize("name", NOTEBOOK_NAMES)
def test_the_committed_notebook_recorded_no_errors(name: str) -> None:
    """A committed traceback means the last execution failed and nobody looked."""
    code = _code_cells(_read(NOTEBOOKS / f"{name}.ipynb"))

    errors = [
        output
        for cell in code
        for output in cell.get("outputs", [])
        if output.get("output_type") == "error"
    ]
    assert not errors, (
        f"{name}: {len(errors)} cell(s) raised on the last execution, "
        f"first was {errors[0].get('ename')}: {errors[0].get('evalue')}"
    )
