"""The Oxford real-cell adapter (v0.6).

The pure core -- pseudo-OCV table, age alignment, measured fade, and the unit-handling of
``_age_from_fields`` -- is exercised here on *synthetic* arrays with no dataset and no optional
dependency, exactly as ``calibration.external``'s self-consistency control needs no PyBaMM. The
one test that touches the real 254 MB ``.mat`` file is marked ``oxford`` and skips unless the data
is present, so the base suite stays green offline.

The load-bearing test is ``test_adapter_pair_is_self_consistent``: feed the adapter two
ECM-generated traces differing only in capacity, and the *unchanged* v0.4 paired estimator must
recover the injected fade with essentially zero lack-of-fit. That the change is in the observer's
own model span is the whole point -- it proves the plumbing, and it is exactly the discipline that
makes a later refusal on real data meaningful rather than a system that refuses everything.
"""

from __future__ import annotations

from pathlib import Path

import numpy as np
import pytest

from astracell.calibration.external import (
    CAPACITY_TARGET,
    build_external_observer,
    external_scenario,
)
from astracell.calibration.positive_control import build_evidence
from astracell.cell.ocv import NMC_LIKE
from astracell.pack.simulate import simulate
from astracell.plant.oxford import (
    OxfordAge,
    _age_from_fields,
    aligned_pair,
    default_mat_path,
    measured_fade,
    pseudo_ocv_curve,
)

_OCV_SOC = np.linspace(0.02, 0.98, 120)
_OCV_V = NMC_LIKE.ocv(_OCV_SOC)


def _synthetic_age(
    cyc: int,
    capacity_ah: float,
    *,
    nominal_ah: float,
    n: int = 800,
    dt: float = 1.0,
    soc0: float = 0.9,
) -> OxfordAge:
    """An OxfordAge whose 1C discharge is generated by the ECM itself at a given capacity.

    The current is fixed 1C of the *nominal* capacity (as in the dataset, where C1dc is a fixed
    740 mA at every age); a lower-capacity cell therefore droops faster under it.
    """
    current = np.full(n, nominal_ah, dtype=float)  # 1C of nominal
    observer = build_external_observer(NMC_LIKE, capacity_ah)
    result = simulate(observer, current, dt, soc0=soc0, temp0_k=298.15)
    return OxfordAge(
        cyc=cyc,
        soc=_OCV_SOC.copy(),
        ocv_v=_OCV_V.copy(),
        time_s=np.arange(n, dtype=float) * dt,
        current_a=current,
        voltage_v=np.asarray(result.voltage_v[:, 0], dtype=float),
        capacity_ah=capacity_ah,
    )


def test_measured_fade_is_signed_relative_deviation() -> None:
    base = _synthetic_age(0, 5.0, nominal_ah=5.0)
    aged = _synthetic_age(100, 4.5, nominal_ah=5.0)
    assert measured_fade(base, aged) == pytest.approx(-0.10)
    assert measured_fade(base, base) == pytest.approx(0.0)


def test_measured_fade_rejects_nonpositive_baseline() -> None:
    bad = OxfordAge(0, _OCV_SOC, _OCV_V, np.arange(4.0), np.ones(4), np.ones(4), capacity_ah=0.0)
    with pytest.raises(ValueError, match="baseline capacity"):
        measured_fade(bad, bad)


def test_pseudo_ocv_curve_interpolates_the_table() -> None:
    age = _synthetic_age(0, 5.0, nominal_ah=5.0)
    curve = pseudo_ocv_curve(age)
    # The reconstructed curve must reproduce the measured table it was built from.
    got = curve.ocv(_OCV_SOC)
    assert np.allclose(got, _OCV_V, atol=1e-6)


def test_pseudo_ocv_curve_monotonizes_duplicate_soc() -> None:
    """A real ~C/18 sweep sampled at 1 Hz repeats SOC where the charge counter holds; the curve
    builder must collapse exact duplicates rather than raise, and invent no points."""
    soc = np.array([0.02, 0.02, 0.30, 0.55, 0.55, 0.55, 0.80, 0.98, 0.98])
    ocv_v = np.array([2.70, 2.70, 3.30, 3.60, 3.60, 3.60, 3.90, 4.20, 4.20])
    age = OxfordAge(0, soc, ocv_v, np.arange(9.0), np.ones(9), np.ones(9), capacity_ah=0.74)
    curve = pseudo_ocv_curve(age)  # would raise "strictly increasing" without the dedup
    assert curve.ocv(np.array([0.55]))[0] == pytest.approx(3.60, abs=1e-6)  # a kept vertex
    assert 3.30 <= curve.ocv(np.array([0.42]))[0] <= 3.60  # interpolated, not invented


def test_aligned_pair_returns_a_common_grid() -> None:
    base = _synthetic_age(0, 5.0, nominal_ah=5.0)
    aged = _synthetic_age(100, 4.5, nominal_ah=5.0)
    current, base_v, aged_v, soc0 = aligned_pair(base, aged, window_s=600.0, dt_s=1.0)
    assert current.shape == base_v.shape == aged_v.shape == (600,)
    # The observer represents SOC only up to ~0.98, so that is where the replay starts.
    assert soc0 == pytest.approx(0.98)
    # The aged cell, emptying faster under the same current, sits lower by the window's end.
    assert aged_v[-1] < base_v[-1]


def test_aligned_pair_rejects_a_window_longer_than_the_discharge() -> None:
    base = _synthetic_age(0, 5.0, nominal_ah=5.0, n=300)
    aged = _synthetic_age(100, 4.5, nominal_ah=5.0, n=300)
    with pytest.raises(ValueError, match="shorter than"):
        aligned_pair(base, aged, window_s=600.0, dt_s=1.0)


def test_age_from_fields_applies_dataset_units() -> None:
    """Pin the units against the real file: q in mAh, and t a MATLAB datenum in *days*.

    A 740 mAh Kokam cell discharged at a constant 1C (740 mA) for one hour must come back as
    ~0.74 Ah of capacity and ~0.74 A of current -- so the mAh->Ah scale, the datenum-days->seconds
    scale (x86400 after subtracting the epoch), and the Ah/s->A (x3600) conversion the coulomb count
    needs must ALL be right, or the observer is handed the wrong plant. The real file's ``t`` is a
    datenum, NOT the "seconds" its Readme claims -- the end-to-end run caught that, and this pins
    what the run found. SOC, a charge ratio, is immune to the units and spans 1->0.
    """
    n = 361
    epoch = 735954.0  # a MATLAB datenum (2015-01-08), as in the real file
    t_days = epoch + np.linspace(0.0, 3600.0 / 86400.0, n)  # one hour, in datenum days
    q_mah = np.linspace(0.0, 740.0, n)  # cumulative charge removed, mAh
    ocvdc = {"t": t_days, "v": np.linspace(4.2, 2.7, n), "q": q_mah}  # full pseudo-OCV sweep
    c1dc = {"t": t_days, "v": np.linspace(4.0, 2.7, n), "q": q_mah}  # 1C discharge
    age = _age_from_fields(200, ocvdc, c1dc)
    assert age.cyc == 200
    assert age.soc[0] == pytest.approx(1.0) and age.soc[-1] == pytest.approx(0.0)
    assert age.capacity_ah == pytest.approx(0.74, abs=1e-3)  # 740 mAh -> Ah
    assert age.time_s[0] == pytest.approx(0.0)  # epoch subtracted
    assert age.time_s[-1] == pytest.approx(3600.0, abs=1.0)  # datenum days -> seconds
    assert np.allclose(age.current_a, 0.74, atol=1e-3)  # constant 1C, in amps


def test_adapter_pair_is_self_consistent() -> None:
    """ECM-generated pair, capacity-only difference: the paired estimator recovers the fade.

    Nothing here is real; that is the point. If the plumbing that will later refuse a real cell
    cannot recover a fault its own model expresses, no refusal would mean anything. The lack-of-fit
    must be ~zero, because a capacity change *is* in the observer's span.
    """
    fade = -0.05
    q_base, dt, soc0 = 5.0, 1.0, 0.9
    base = _synthetic_age(0, q_base, nominal_ah=q_base, soc0=soc0)
    aged = _synthetic_age(100, q_base * (1.0 + fade), nominal_ah=q_base, soc0=soc0)

    # Replay from the same SOC the synthetic traces were generated at: a soc0 mismatch would itself
    # manufacture lack-of-fit and rob the self-consistency check of its meaning.
    current, base_v, aged_v, s0 = aligned_pair(base, aged, window_s=600.0, dt_s=dt, soc0=soc0)
    scenario = external_scenario(
        name="oxford_self_consistency",
        observer=build_external_observer(NMC_LIKE, q_base),
        current_a=current,
        soc0=s0,
        dt_s=dt,
        fault_magnitude=measured_fade(base, aged),
        target_index=CAPACITY_TARGET,
    )
    evidence = build_evidence(scenario, base_v, aged_v)

    assert evidence.delta_true == pytest.approx(fade)
    assert evidence.paired_estimate == pytest.approx(fade, abs=5e-3)
    # A capacity change is the observer's *own* parameter, so the lack-of-fit screen stays in its
    # "expressible" regime. lack_of_fit_norm reads in the hundreds for a change the ECM cannot
    # reproduce (see PairedEvidence); here it is ~0.07 -- the residual curvature of a finite 5%
    # step, which shrinks quadratically as the step does. Recovery, not exact linearity, is claimed.
    assert evidence.misfit_paired < 1.0


@pytest.mark.oxford
def test_load_cell_parses_a_synthetic_oxford_mat(tmp_path: Path) -> None:
    """Drive the real .mat reader (scipy branch) on a synthetic file in the exact Oxford struct.

    The 254 MB dataset is v7.3/HDF5 and takes the h5py branch, which needs the download; but the
    scipy branch and the struct navigation are the same logic and are testable here on a small
    old-format .mat that scipy can write. This covers load_cell -> load_cells -> _read_mat_cells ->
    _walk_scipy_struct -> _age_from_fields end to end -- including the mAh->Ah scaling through the
    real reader, not just the pure helper -- with no download and no fabricated data.
    """
    scipy_io = pytest.importorskip("scipy.io")

    def discharge(cap_ah: float, n: int = 200) -> dict[str, np.ndarray]:
        return {
            "t": np.linspace(0.0, 3600.0, n),
            "v": np.linspace(4.1, 2.7, n),
            "q": np.linspace(0.0, cap_ah * 1000.0, n),  # cumulative charge removed, mAh
            "T": np.full(n, 40.0),
        }

    cell = {
        "cyc0100": {"C1dc": discharge(0.74), "OCVdc": discharge(0.74)},
        "cyc0300": {"C1dc": discharge(0.66), "OCVdc": discharge(0.66)},
    }
    path = tmp_path / "synth.mat"
    scipy_io.savemat(str(path), {"Cell1": cell})

    from astracell.plant.oxford import load_cell

    ages = load_cell(str(path), "Cell1")
    assert sorted(ages) == [100, 300]
    assert ages[100].capacity_ah == pytest.approx(0.74, abs=1e-3)  # mAh -> Ah through the reader
    assert ages[300].capacity_ah == pytest.approx(0.66, abs=1e-3)
    assert measured_fade(ages[100], ages[300]) == pytest.approx((0.66 - 0.74) / 0.74, abs=1e-3)
    assert ages[100].soc.min() >= 0.0 and ages[100].soc.max() <= 1.0


@pytest.mark.oxford
def test_load_cells_reads_every_cell_in_one_pass(tmp_path: Path) -> None:
    """``load_cells`` reads a multi-cell file once and agrees with ``load_cell`` per cell.

    ``examples/08`` scores all eight cells; ``load_cells`` exists so the 254 MB file is opened once
    rather than once per cell. This drives the multi-cell path on a synthetic two-cell file: both
    cells come back, keyed and sorted, in the requested order, and each matches what the single-cell
    wrapper returns -- the guarantee that lets the example trust one pass over eight.
    """
    scipy_io = pytest.importorskip("scipy.io")

    def discharge(cap_ah: float, n: int = 200) -> dict[str, np.ndarray]:
        return {
            "t": np.linspace(0.0, 3600.0, n),
            "v": np.linspace(4.1, 2.7, n),
            "q": np.linspace(0.0, cap_ah * 1000.0, n),  # cumulative charge removed, mAh
            "T": np.full(n, 40.0),
        }

    mat = {
        "Cell1": {"cyc0100": {"C1dc": discharge(0.74), "OCVdc": discharge(0.74)}},
        "Cell2": {
            "cyc0100": {"C1dc": discharge(0.73), "OCVdc": discharge(0.73)},
            "cyc0500": {"C1dc": discharge(0.61), "OCVdc": discharge(0.61)},
        },
    }
    path = tmp_path / "multi.mat"
    scipy_io.savemat(str(path), mat)

    from astracell.plant.oxford import load_cell, load_cells

    got = load_cells(str(path), ["Cell2", "Cell1"])  # request order preserved, not file order
    assert list(got) == ["Cell2", "Cell1"]
    assert sorted(got["Cell1"]) == [100]
    assert sorted(got["Cell2"]) == [100, 500]
    assert got["Cell2"][500].capacity_ah == pytest.approx(0.61, abs=1e-3)  # mAh -> Ah, second cell
    # One pass over two cells must equal two single-cell loads: the shared assembly cannot drift.
    solo = load_cell(str(path), "Cell2")
    assert sorted(solo) == sorted(got["Cell2"])
    assert solo[500].capacity_ah == pytest.approx(got["Cell2"][500].capacity_ah)


@pytest.mark.oxford
def test_load_cell_reads_the_real_mat() -> None:
    """Only runs where the 254 MB dataset is present and scipy/h5py exist.

    Looks at ``default_mat_path()`` (``ASTRACELL_OXFORD_MAT`` or the gitignored ``data/oxford/``
    written by ``scripts/fetch_oxford.py``). Verifies the .mat shell against the real file -- struct
    navigation and, critically, the unit assumptions in ``_age_from_fields`` that cannot be checked
    synthetically.
    """
    path = default_mat_path()
    if not path.exists():
        pytest.skip(f"no Oxford .mat at {path}; run scripts/fetch_oxford.py or set the env var")
    pytest.importorskip("scipy")

    from astracell.plant.oxford import load_cell

    ages = load_cell(str(path), "Cell1")
    assert len(ages) >= 2
    cycs = sorted(ages)
    base, aged = ages[cycs[0]], ages[cycs[-1]]
    # Kokam cells are ~0.74 Ah and fade to ~30% loss by end of life; sanity-bound both.
    assert 0.3 < base.capacity_ah < 1.2
    assert measured_fade(base, aged) < 0.0  # it aged; capacity fell
    assert base.soc.min() >= 0.0 and base.soc.max() <= 1.0
